const products = [
  {
    id: 1,
    name: "Basic Tee",
    category: "men",
    href: "#",
    colors: ["red", "blue", "black"],
    imageSrc:
      "https://tailwindui.com/img/ecommerce-images/product-page-01-related-product-01.jpg",
    imageAlt: "Front of men's Basic Tee in black.",
    price: 35,
    color: "Black",
    sizes: [
      { name: "XXS", inStock: false },
      { name: "XS", inStock: true },
      { name: "S", inStock: true },
      { name: "M", inStock: true },
      { name: "L", inStock: true },
      { name: "XL", inStock: true },
      { name: "2XL", inStock: true },
      { name: "3XL", inStock: true },
    ],
    quantity: 1,
  },
  {
    id: 2,
    name: "Nike Sneakers",
    category: "men",
    colors: ["red", "blue", "black"],
    href: "#",
    imageSrc:
      "https://images.unsplash.com/photo-1491553895911-0055eca6402d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8OHx8bmlrZXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
    imageAlt: "Black Nike sneakers",
    price: 150,
    color: "Black",
    sizes: [
      { name: "XXS", inStock: false },
      { name: "XS", inStock: true },
      { name: "S", inStock: true },
      { name: "M", inStock: true },
      { name: "L", inStock: true },
      { name: "XL", inStock: true },
      { name: "2XL", inStock: true },
      { name: "3XL", inStock: true },
    ],
    quantity: 1,
  },
  {
    id: 3,
    name: "Levi's Jeans",
    category: "men",
    colors: ["red", "blue", "black"],
    href: "#",
    imageSrc:
      "https://images.unsplash.com/photo-1605518216938-7c31b7b14ad0?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8ZGVuaW0lMjBqZWFuc3xlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
    imageAlt: "Black Nike sneakers",
    price: 50,
    color: "Light Blue",
    sizes: [
      { name: "XXS", inStock: false },
      { name: "XS", inStock: true },
      { name: "S", inStock: true },
      { name: "M", inStock: true },
      { name: "L", inStock: true },
      { name: "XL", inStock: true },
      { name: "2XL", inStock: true },
      { name: "3XL", inStock: true },
    ],
    quantity: 1,
  },
  {
    id: 4,
    name: "Levi's Denim Jacket",
    category: "men",
    colors: ["red", "blue", "black"],
    href: "#",
    imageSrc:
      "https://images.unsplash.com/photo-1611312449408-fcece27cdbb7?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8amFja2V0fGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
    imageAlt: "Premium Levi's Denim Jacket",
    price: 120,
    color: "Blue",
    sizes: [
      { name: "XXS", inStock: false },
      { name: "XS", inStock: true },
      { name: "S", inStock: true },
      { name: "M", inStock: true },
      { name: "L", inStock: true },
      { name: "XL", inStock: true },
      { name: "2XL", inStock: true },
      { name: "3XL", inStock: true },
    ],
    quantity: 1,
  },
  {
    id: 5,
    name: "Black Womens Skirt",
    category: "women",
    colors: ["red", "blue", "black"],
    href: "#",
    imageSrc:
      "https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8OXx8c2tpcnRzfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
    imageAlt: "Black Womens Skirt",
    price: 80,
    color: "Black",
    sizes: [
      { name: "XXS", inStock: false },
      { name: "XS", inStock: true },
      { name: "S", inStock: true },
      { name: "M", inStock: true },
      { name: "L", inStock: true },
      { name: "XL", inStock: true },
      { name: "2XL", inStock: true },
      { name: "3XL", inStock: true },
    ],
    quantity: 1,
  },
  {
    id: 6,
    name: "Womens High Heels",
    category: "women",
    colors: ["red", "blue", "black"],
    href: "#",
    imageSrc:
      "https://images.unsplash.com/photo-1618274158630-bc47a614b3a5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NDZ8fHNhbmRhbHN8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
    imageAlt: "Black Womens High Heels",
    price: 220,
    color: "Black",
    sizes: [
      { name: "XXS", inStock: false },
      { name: "XS", inStock: true },
      { name: "S", inStock: true },
      { name: "M", inStock: true },
      { name: "L", inStock: true },
      { name: "XL", inStock: true },
      { name: "2XL", inStock: true },
      { name: "3XL", inStock: true },
    ],
    quantity: 1,
  },

  {
    id: 7,
    name: "New Trend Dress",
    category: "women",
    colors: ["red", "blue", "black"],
    href: "#",
    imageSrc:
      "https://images.unsplash.com/photo-1616313253719-c46514cddee1?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Nnx8d29tZW5zJTIwY2xvdGhlc3xlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
    imageAlt: "Black Womens High Heels",
    price: 170,
    color: "Misc",
    sizes: [
      { name: "XXS", inStock: false },
      { name: "XS", inStock: true },
      { name: "S", inStock: true },
      { name: "M", inStock: true },
      { name: "L", inStock: true },
      { name: "XL", inStock: true },
      { name: "2XL", inStock: true },
      { name: "3XL", inStock: true },
    ],
    quantity: 1,
  },
  {
    id: 8,
    name: "Black & Gray Flannel Shirt",
    category: "men",
    colors: ["red", "blue", "black"],
    href: "#",
    imageSrc:
      "https://images.unsplash.com/photo-1611312449412-6cefac5dc3e4?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8ODN8fGNsb3RoZXN8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
    imageAlt: "Black Womens High Heels",
    price: 95,
    color: "Gray & Black",
    sizes: [
      { name: "XXS", inStock: false },
      { name: "XS", inStock: true },
      { name: "S", inStock: true },
      { name: "M", inStock: true },
      { name: "L", inStock: true },
      { name: "XL", inStock: true },
      { name: "2XL", inStock: true },
      { name: "3XL", inStock: true },
    ],
    quantity: 1,
  },
  {
    id: 9,
    name: "Poncho Hanger",
    category: "women",
    colors: ["red", "blue", "black"],
    href: "#",
    imageSrc:
      "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8OHx8Y2xvdGhlc3xlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
    imageAlt: "High quality Poncho Hanger",
    price: 80,
    color: "Off White",
    sizes: [
      { name: "XXS", inStock: false },
      { name: "XS", inStock: true },
      { name: "S", inStock: true },
      { name: "M", inStock: true },
      { name: "L", inStock: true },
      { name: "XL", inStock: true },
      { name: "2XL", inStock: true },
      { name: "3XL", inStock: true },
    ],
    quantity: 1,
  },
  {
    id: 10,
    name: "All color mens sweatshirts",
    category: "men",
    colors: ["red", "blue", "black"],
    href: "#",
    imageSrc:
      "https://images.unsplash.com/photo-1562157873-818bc0726f68?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=327&q=80",
    imageAlt: "Black Womens High Heels",
    price: 40,
    color: "All colors",
    sizes: [
      { name: "XXS", inStock: false },
      { name: "XS", inStock: true },
      { name: "S", inStock: true },
      { name: "M", inStock: true },
      { name: "L", inStock: true },
      { name: "XL", inStock: true },
      { name: "2XL", inStock: true },
      { name: "3XL", inStock: true },
    ],
    quantity: 1,
  },
];

export default products;
